# -*- coding: utf-8 -*-
"""project3_restaurant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pkqy4YyA5bn3b0xnFzgyJjnul4FFDT94

import libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from sklearn.model_selection import TimeSeriesSplit, GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
import xgboost as xgb
from prophet import Prophet
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.statespace.sarimax import SARIMAX
from statsmodels.tsa.holtwinters import ExponentialSmoothing

sales = pd.read_csv("restaurant_sales.csv", parse_dates=["date"])
weather = pd.read_csv("Daily_Weather_Insights.csv", parse_dates=["Date"])
holidays = pd.read_csv("Global_Holidays_2025_2035.csv", parse_dates=["Date"])

weather.rename(columns={"Date":"date"}, inplace=True)
holidays.rename(columns={"Date":"date"}, inplace=True)

print(sales.head(5))

sales.index=sales['date']

print(sales.head(5))

del sales['date']

print(sales.head(5))

sales.isnull().sum().sum()

sales.duplicated().sum()

sales.drop_duplicates(inplace=True)

sales.duplicated().sum()

print(weather.head(5))

weather.index=weather['date']

del weather['date']

print(weather.head(5))

weather.isnull().sum().sum()

weather.duplicated().sum()

print(weather.info())

print(holidays.head(5))

holidays['date'] = pd.to_datetime(holidays['date'], format='%Y-%m-%d', errors='coerce')

holidays = holidays[holidays['date'].between('2025-01-01','2028-12-31')]

holidays.index=holidays['date']

del holidays['date']
del holidays['Local_Name']

del holidays['Year']

holidays.info()

holidays.isnull().sum().sum()

holidays.duplicated().sum()

holidays.shape

# Merge sales with weather and holidays
df = sales.merge(weather, on="date", how="left")
df = df.merge(holidays, on="date", how="left")

df.head(5)

df['Country'].unique()

df['Country'] = df['Country'].fillna('IN')
df['Holiday_Name'] = df['Holiday_Name'].fillna('No Holiday')
df['Type'] = df['Type'].fillna('No Type')

numeric_cols = df.select_dtypes(include=np.number).columns
df[numeric_cols] = df[numeric_cols].fillna(0)
print(df.isnull().sum().sum())

df.dropna(inplace=True)

df = df.sort_values(by='date')

print(df.columns)

df.describe()

def detect_outliers_iqr(df):
    outlier_dict = {}
    for col in df.select_dtypes(include=['float64','int64']).columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)][col]
        outlier_dict[col] = outliers
    return outlier_dict

# Example usage:
outliers = detect_outliers_iqr(df)
for col, vals in outliers.items():
    print(f"Column: {col}, Outliers count: {len(vals)}")
    print(vals.values[:10])  # show first 10 outlier values

def handle_outliers(df, method="flag", action="keep"):
    """
    Detects outliers in all numeric columns using IQR.
    Parameters:
        df (DataFrame): your dataset
        method (str): 'iqr' (default) or 'zscore'
        action (str): 'keep', 'remove', or 'cap'
    Returns:
        DataFrame with outliers handled according to action
    """
    df_out = df.copy()
    numeric_cols = df_out.select_dtypes(include=['float64','int64']).columns

    for col in numeric_cols:
        Q1 = df_out[col].quantile(0.25)
        Q3 = df_out[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5*IQR
        upper_bound = Q

plt.figure(figsize=(14,6))
sns.lineplot(x='date', y='sales', data=df, marker='o')

plt.title("Restaurant Sales Over Time")
plt.xlabel("Date")
plt.ylabel("Daily Sales")
plt.grid(True)
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose

# Assume sales is your target column
result = seasonal_decompose(df['sales'], model='additive', period=7)  # weekly seasonality
result.plot()
plt.show()

import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# Plot ACF (autocorrelation function)
plt.figure(figsize=(12,4))
plot_acf(df['sales'].dropna(), lags=30)  # up to 30 lags
plt.title("Autocorrelation (ACF) of Sales")
plt.show()

# Plot PACF (partial autocorrelation function)
plt.figure(figsize=(12,4))
plot_pacf(df['sales'].dropna(), lags=30)
plt.title("Partial Autocorrelation (PACF) of Sales")
plt.show()

#Feature engineering

# Create lag features for sales
df['lag1'] = df['sales'].shift(1)   # previous day
df['lag7'] = df['sales'].shift(7)   # same day last week
df['lag30'] = df['sales'].shift(30) # same day last month

# Impute NA values introduced by shifting to retain data
df = df.infer_objects(copy=False) # Infer object dtypes before interpolating
df = df.interpolate(method='linear', limit_direction='both')
df = df.ffill()
df = df.bfill()

# Rolling averages for sales
df['sales_roll3'] = df['sales'].rolling(window=3).mean()   # 3-day average
df['sales_roll7'] = df['sales'].rolling(window=7).mean()   # 7-day average (weekly)
df['sales_roll30'] = df['sales'].rolling(window=30).mean() # 30-day average (monthly)

# Impute NA values introduced by rolling windows to retain data
df = df.infer_objects(copy=False) # Infer object dtypes before interpolating
df = df.interpolate(method='linear', limit_direction='both')
df = df.ffill()
df = df.bfill()

# This cell is removed as its functionality is now covered and improved in previous cells.

import pandas as pd
from pandas.tseries.holiday import USFederalHolidayCalendar

# Example: US holidays (replace with your country’s calendar if needed)
cal = USFederalHolidayCalendar()
holidays = cal.holidays(start=df.index.min(), end=df.index.max())

# Create a 'date' column from the index for easier manipulation
df['date'] = df.index
df['is_holiday'] = df['date'].isin(holidays).astype(int)
del df['date'] # delete the temporary 'date' column after use

# Flag weekends (Saturday=5, Sunday=6)
df['is_weekend'] = df.index.weekday.isin([5,6]).astype(int)

"""1 → weekend

0 → weekday
"""

from statsmodels.tsa.stattools import adfuller

# Run ADF test on sales column
result = adfuller(df['sales'].dropna())

print('ADF Statistic:', result[0])
print('p-value:', result[1])
print('Critical Values:', result[4])

"""p-value < 0.05 → reject null hypothesis → series is stationary.

p-value ≥ 0.05 → fail to reject null → series is non-stationary (needs
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Example categorical feature: day of week
df['day_of_week'] = df.index.day_name() # Use df.index instead of df['date']

# Initialize label encoder
le = LabelEncoder()

# Fit and transform
df['day_of_week_encoded'] = le.fit_transform(df['day_of_week'])

# Check mapping
mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print("Label Encoding Mapping:", mapping)

# One-hot encode remaining categorical features
categorical_cols_to_encode = ['City', 'Weather_Condition', 'Country', 'Holiday_Name', 'Type']
df = pd.get_dummies(df, columns=categorical_cols_to_encode, drop_first=True)

# Display the first few rows and column names to confirm changes
print(df.head())
print(df.columns)

"""### Re-running Classical Models with Improved Imputation

model selection
"""

#classical statistical model

# Train-test split (last 20% as test)
train_size = int(len(df) * 0.8)
train, test = df.iloc[:train_size], df.iloc[train_size:]

y_train, y_test = train['sales'], test['sales']

#--- 1. ARIMA ---
arima_model = ARIMA(y_train, order=(5,1,0))   # Changed order to (5,1,0) as y_train is too small for (2,1,2)
arima_fit = arima_model.fit()
arima_pred = arima_fit.forecast(steps=len(y_test))

# Ensure arima_pred has the same index as y_test for plotting
arima_pred.index = y_test.index

plt.figure(figsize=(14,6))
plt.plot(y_test.index, y_test, label="Actual", color="black")
plt.plot(y_test.index, arima_pred, label="ARIMA Forecast", color="blue")
plt.title("ARIMA Forecast vs Actual")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.legend()
plt.show()

!pip install numpy==1.26.4

!pip install pmdarima

from pmdarima import auto_arima
auto=auto_arima(y_train, trace=True, suppress_warnings=True)
auto.summary()

#--- 2. SARIMAX ---
sarimax_model = SARIMAX(y_train, order=(4,0,0), seasonal_order=(1,1,1,7))  # weekly seasonality
sarimax_fit = sarimax_model.fit()
sarimax_pred = sarimax_fit.forecast(steps=len(test))

# --- Evaluation with RMSE AND MAE ---
def evaluate(y_true, y_pred, model_name):
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)
    print(f"{model_name} → RMSE: {rmse:.2f}, MAE: {mae:.2f}")
    return {"model_name": model_name, "rmse": rmse, "mae": mae}

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.statespace.sarimax import SARIMAX

# Re-define train-test split (from cell jVWMb8qcPfNe)
train_size = int(len(df) * 0.8)
train, test = df.iloc[:train_size], df.iloc[train_size:]
y_train, y_test = train['sales'], test['sales']

# Re-generate ARIMA predictions (from cell be6DbD8hRyaV)
arima_model = ARIMA(y_train, order=(5,1,0))
arima_fit = arima_model.fit()
arima_pred = arima_fit.forecast(steps=len(y_test))
arima_pred.index = y_test.index

# Re-generate SARIMAX predictions (from cell tZycLx4YPfKl)
sarimax_model = SARIMAX(y_train, order=(4,0,0), seasonal_order=(1,1,1,7))
sarimax_fit = sarimax_model.fit()
sarimax_pred = sarimax_fit.forecast(steps=len(test))

# --- Plot comparison ---
plt.figure(figsize=(14,6))
plt.plot(y_test.index, y_test, label="Actual", color="black")
plt.plot(arima_pred.index, arima_pred, label="ARIMA Forecast", color="blue")

# Align sarimax_pred index to the actual test data index for plotting
sarimax_pred.index = y_test.index
plt.plot(sarimax_pred.index, sarimax_pred, label="SARIMAX Forecast", color="green")

plt.title("Forecast Comparison")
plt.legend()
plt.show()

import pandas as pd
from prophet import Prophet
from pandas.tseries.holiday import USFederalHolidayCalendar
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
import matplotlib.pyplot as plt

# Prepare DataFrame for Prophet (rename 'date' to 'ds' and 'sales' to 'y')
df_prophet = df.reset_index().rename(columns={'date': 'ds', 'sales': 'y'})

# Add holiday effects (example: US holidays)
cal = USFederalHolidayCalendar()
holidays = pd.DataFrame({
    'holiday': 'USFederalHoliday',
    'ds': cal.holidays(start=df_prophet['ds'].min(), end=df_prophet['ds'].max()),
    'lower_window': 0,
    'upper_window': 1,
})

# Initialize Prophet model with all desired parameters and holidays
m = Prophet(
    yearly_seasonality=True,   # yearly patterns
    weekly_seasonality=True,   # weekly patterns
    daily_seasonality=False,   # set True if you have hourly data
    holidays=holidays
)

# Fit the model
m.fit(df_prophet)

# Make future dataframe (forecast horizon = 30 days)
future = m.make_future_dataframe(periods=30)
forecast = m.predict(future)

# Evaluate on test set (last 20%)
train_size = int(len(df_prophet) * 0.8)

# Get the actual values for the test set, handling duplicate 'ds' by taking the mean.
# This creates a Series `y_test_actuals` indexed by unique 'ds' values.
y_test_actuals = df_prophet.iloc[train_size:].groupby('ds')['y'].mean()

# Filter the forecast to get predictions for these unique test dates.
# This ensures that y_pred_forecast is aligned with y_test_actuals in terms of 'ds' and uniqueness.
y_pred_forecast = forecast[forecast['ds'].isin(y_test_actuals.index)].set_index('ds')['yhat']

# Align both series to their common index (which should be identical now)
# This step ensures they have the same order and length before calculating metrics.
common_dates = y_test_actuals.index.intersection(y_pred_forecast.index)
y_test_final = y_test_actuals.loc[common_dates]
y_pred_final = y_pred_forecast.loc[common_dates]

# Define y_test_prophet and y_pred_prophet for consistency with later plotting cells
y_test_prophet = y_test_final
y_pred_prophet = y_pred_final

rmse = np.sqrt(mean_squared_error(y_test_final, y_pred_final))
mae = mean_absolute_error(y_test_final, y_pred_final)
print(f"Prophet → RMSE: {rmse:.2f}, MAE: {mae:.2f}")

# Plot forecast
fig1 = m.plot(forecast)
plt.title("Prophet Forecast with Holidays")
plt.show()

# Plot components (trend, weekly, yearly, holidays)
fig2 = m.plot_components(forecast)
plt.show()

"""### Visualize Prophet Model Performance"""

# Plot the actual values vs. Prophet forecast for the test set
plt.figure(figsize=(14, 6))
plt.plot(y_test_prophet.index, y_test_prophet, label='Actual Sales', color='black')
plt.plot(y_test_prophet.index, y_pred_prophet, label='Prophet Forecast', color='blue', linestyle='--')
plt.title('Prophet Model: Actual vs. Forecasted Sales (Test Set)')
plt.xlabel('Date')
plt.ylabel('Sales')
plt.legend()
plt.grid(True)
plt.show()

residuals_prophet = y_test_prophet - y_pred_prophet

residuals_prophet.head()

# Ensure y_test_prophet and y_pred_prophet are aligned by index
common_index = y_test_prophet.index.intersection(y_pred_prophet.index)

y_test_aligned = y_test_prophet.loc[common_index]
y_pred_aligned = y_pred_prophet.loc[common_index]

# Calculate residuals with aligned series
residuals_prophet = y_test_aligned - y_pred_aligned

# Visualize residuals
plt.figure(figsize=(14, 6))
plt.subplot(1, 2, 1)
sns.histplot(residuals_prophet, kde=True)
plt.title('Prophet Model: Residuals Distribution')
plt.xlabel('Residuals')
plt.ylabel('Frequency')

plt.subplot(1, 2, 2)
plt.scatter(y_pred_aligned, residuals_prophet, alpha=0.7)
plt.axhline(0, color='red', linestyle='--')
plt.title('Prophet Model: Residuals vs. Forecast')
plt.xlabel('Forecasted Sales')
plt.ylabel('Residuals')
plt.grid(True)

plt.tight_layout()
plt.show()

import joblib

# Save the Prophet model
joblib.dump(m, 'prophet_model.joblib')
print("Prophet model saved to prophet_model.joblib")

#Linear Regression Model as base model
 #Prepare data for Linear Regression
# Features are all columns except 'sales' and 'day_of_week'
features_lr = [col for col in df.columns if col not in ['sales', 'day_of_week']]
X_lr = df[features_lr]
y_lr = df['sales']

# Split data using TimeSeriesSplit to maintain temporal order
tscv_lr = TimeSeriesSplit(n_splits=2)
for train_index_lr, test_index_lr in tscv_lr.split(X_lr):
    X_train_lr, X_test_lr = X_lr.iloc[train_index_lr], X_lr.iloc[test_index_lr]
    y_train_lr, y_test_lr = y_lr.iloc[train_index_lr], y_lr.iloc[test_index_lr]

print(f"X_train_lr shape: {X_train_lr.shape}")
print(f"X_test_lr shape: {X_test_lr.shape}")
print(f"y_train_lr shape: {y_train_lr.shape}")
print(f"y_test_lr shape: {y_test_lr.shape}")

#Initialize and train the Linear Regression model
lr_model = LinearRegression()
lr_model.fit(X_train_lr, y_train_lr)

# Make predictions on the test set
lr_pred = lr_model.predict(X_test_lr)

# Evaluate the model
rmse_lr = np.sqrt(mean_squared_error(y_test_lr, lr_pred))
mae_lr = mean_absolute_error(y_test_lr, lr_pred)

print(f"Linear Regression → RMSE: {rmse_lr:.2f}, MAE: {mae_lr:.2f}")

# Visualize Linear Regression Model Performance
y_pred_lr_series = pd.Series(lr_pred, index=y_test_lr.index)

plt.figure(figsize=(14, 6))
plt.plot(y_test_lr.index, y_test_lr, label='Actual Sales', color='black')
plt.plot(y_test_lr.index, y_pred_lr_series, label='Linear Regression Forecast', color='purple', linestyle='--')
plt.title('Linear Regression Model: Actual vs. Forecasted Sales (Test Set)')
plt.xlabel('Date')
plt.ylabel('Sales')
plt.legend()
plt.grid(True)
plt.show()

# Prepare data for XGBoost
# Features are all columns except 'sales' and 'day_of_week' (since we have 'day_of_week_encoded')
features = [col for col in df.columns if col not in ['sales', 'day_of_week']]
X = df[features]
y = df['sales']

# Split data using TimeSeriesSplit to maintain temporal order
tscv = TimeSeriesSplit(n_splits=2) # Using a small split for demonstration, adjust as needed
for train_index, test_index in tscv.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

# Initialize and train the XGBoost Regressor
# Using parameters known to work well from previous runs or default for a quick start
xgb_model = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=100, learning_rate=0.1, random_state=42)
xgb_model.fit(X_train, y_train)

# Make predictions on the test set
xgb_pred = xgb_model.predict(X_test)

# Evaluate the model
rmse_xgb = np.sqrt(mean_squared_error(y_test, xgb_pred))
mae_xgb = mean_absolute_error(y_test, xgb_pred)

print(f"XGBoost → RMSE: {rmse_xgb:.2f}, MAE: {mae_xgb:.2f}")

# Visualize Feature Importances
importance_df = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': xgb_model.feature_importances_
}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(12, 8))
sns.barplot(x='Importance', y='Feature', data=importance_df)
plt.title('XGBoost Feature Importances')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

y_pred_xgb_series = pd.Series(xgb_pred, index=y_test.index)

plt.figure(figsize=(14, 6))
plt.plot(y_test.index, y_test, label='Actual Sales', color='black')
plt.plot(y_test.index, y_pred_xgb_series, label='XGBoost Forecast', color='green', linestyle='--')
plt.title('XGBoost Model: Actual vs. Forecasted Sales (Test Set)')
plt.xlabel('Date')
plt.ylabel('Sales')
plt.legend()
plt.grid(True)
plt.show()

"""Hyperparameter Tuning (Random Forest) with Time-Series Cross-Validation"""

from sklearn.model_selection import GridSearchCV, TimeSeriesSplit
from sklearn.ensemble import RandomForestRegressor

# Define the parameter grid for Random Forest
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [5, 10, 15],
    'min_samples_leaf': [1, 2, 4]
}

# Initialize TimeSeriesSplit for internal GridSearchCV cross-validation
tscv_gs = TimeSeriesSplit(n_splits=3)  # Adjust n_splits based on data size and desired rigor

# Initialize GridSearchCV with RandomForestRegressor
grid_search = GridSearchCV(
    estimator=RandomForestRegressor(random_state=42),
    param_grid=param_grid,
    cv=tscv_gs,  # Use tscv_gs for GridSearchCV's internal cross-validation
    scoring='neg_root_mean_squared_error',  # Optimize for RMSE
    n_jobs=-1,  # Use all available cores
    verbose=1
)

features = [col for col in df.columns if col not in ['sales', 'day_of_week']]
X_ml = df[features]
y_ml = df['sales']

tscv_split = TimeSeriesSplit(n_splits=2)
for train_index, test_index in tscv_split.split(X_ml):
    X_train_rf, X_test_rf = X_ml.iloc[train_index], X_ml.iloc[test_index]
    y_train_rf, y_test_rf = y_ml.iloc[train_index], y_ml.iloc[test_index]

# Fit GridSearchCV to the training data
grid_search.fit(X_train_rf, y_train_rf)

# Get the best parameters and best score
best_params = grid_search.best_params_
best_rmse = -grid_search.best_score_  # Convert negative RMSE back to positive

print(f"Best Parameters: {best_params}")
print(f"Best RMSE (Cross-Validation): {best_rmse:.2f}")

"""### Evaluate Tuned Random Forest Model"""

# Train the Random Forest model with the best parameters
tuned_rf_model = RandomForestRegressor(**best_params, random_state=42)
tuned_rf_model.fit(X_train_rf, y_train_rf)

# Make predictions on the test set
rf_tuned_pred = tuned_rf_model.predict(X_test_rf)

# Evaluate the tuned model
rmse_rf_tuned = np.sqrt(mean_squared_error(y_test_rf, rf_tuned_pred))
mae_rf_tuned = mean_absolute_error(y_test_rf, rf_tuned_pred)

print(f"Tuned Random Forest → RMSE: {rmse_rf_tuned:.2f}, MAE: {mae_rf_tuned:.2f}")

# --- Collect and organize all model results ---

# Ensure we use the correct y_test for classical models (from the initial split, cell jVWMb8qcPfNe)
# The `test` variable in the kernel state refers to df.iloc[train_size:] and has 19 rows.
y_test_classical_split = test['sales']

# Metrics for classical models (ARIMA, SARIMAX)
# Use y_test_classical_split (length 19) to align with predictions (length 19)
rmse_arima = np.sqrt(mean_squared_error(y_test_classical_split, arima_pred))
mae_arima = mean_absolute_error(y_test_classical_split, arima_pred)

rmse_sarimax = np.sqrt(mean_squared_error(y_test_classical_split, sarimax_pred))
mae_sarimax = mean_absolute_error(y_test_classical_split, sarimax_pred)

# Metrics for Prophet (already calculated as 'rmse' and 'mae' in kernel state, using y_test_prophet, y_pred_prophet)
# These are `rmse` and `mae` variables from the previous cell's execution result
rmse_prophet = rmse
mae_prophet = mae

# Metrics for XGBoost (already calculated as 'rmse_xgb' and 'mae_xgb' in kernel state)
rmse_xgb_val = rmse_xgb
mae_xgb_val = mae_xgb

# Create performance_df with all model results
performance_data = [
    {"model_name": "ARIMA", "rmse": rmse_arima, "mae": mae_arima},
    {"model_name": "SARIMAX", "rmse": rmse_sarimax, "mae": mae_sarimax},
    {"model_name": "Prophet", "rmse": rmse_prophet, "mae": mae_prophet},
    {"model_name": "XGBoost", "rmse": rmse_xgb_val, "mae": mae_xgb_val},
    {"model_name": "Random Forest (Tuned)", "rmse": rmse_rf_tuned, "mae": mae_rf_tuned}
]
performance_df = pd.DataFrame(performance_data)

# Display updated comparison table
print("\n--- Updated Model Performance Comparison ---")
print(performance_df.sort_values(by='rmse'))

"""### Visualize Tuned Random Forest Model Residuals"""

residuals_rf = y_test_rf - rf_tuned_pred

plt.figure(figsize=(14, 6))
plt.subplot(1, 2, 1)
sns.histplot(residuals_rf, kde=True)
plt.title('Tuned Random Forest Model: Residuals Distribution')
plt.xlabel('Residuals')
plt.ylabel('Frequency')

plt.subplot(1, 2, 2)
plt.scatter(rf_tuned_pred, residuals_rf, alpha=0.7)
plt.axhline(0, color='red', linestyle='--')
plt.title('Tuned Random Forest Model: Residuals vs. Forecast')
plt.xlabel('Forecasted Sales')
plt.ylabel('Residuals')
plt.grid(True)

plt.tight_layout()
plt.show()

"""### Visualize Tuned Random Forest Feature Importances"""

# Get feature importances from the tuned Random Forest model
rf_feature_importances = pd.DataFrame({
    'Feature': X_train_rf.columns,
    'Importance': tuned_rf_model.feature_importances_
}).sort_values(by='Importance', ascending=False)

# Plot feature importances
plt.figure(figsize=(12, 8))
sns.barplot(x='Importance', y='Feature', data=rf_feature_importances)
plt.title('Tuned Random Forest Feature Importances')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

# Add Linear Regression results to performance_df
new_lr_row = pd.DataFrame([{"model_name": "Linear Regression", "rmse": rmse_lr, "mae": mae_lr}])
performance_df = pd.concat([performance_df, new_lr_row], ignore_index=True)

# Display updated comparison table
print("\n--- Updated Model Performance Comparison ---")
print(performance_df.sort_values(by='rmse'))

"""## Impact of Weather Variables on Sales"""

weather_cols = [
    'Temperature_High (°C)',
    'Temperature_Low (°C)',
    'Humidity (%)',
    'Wind_Speed (km/h)',
    'Precipitation (mm)',
    'Visibility (km)',
    'Air_Quality_Index'
]

plt.figure(figsize=(15, 10))
for i, col in enumerate(weather_cols):
    plt.subplot(3, 3, i + 1)  # Create a 3x3 grid of subplots
    sns.scatterplot(x=col, y='sales', data=df)
    plt.title(f'Sales vs. {col}')
    plt.xlabel(col)
    plt.ylabel('Sales')
    plt.grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

import joblib

# Load the Prophet model
loaded_prophet_model = joblib.load('prophet_model.joblib')

# Create a future DataFrame for forecasting (e.g., 30 days into the future)
# Ensure the last date in prophet_df is used as the starting point for make_future_dataframe
# prophet_df has already been created and used to train the model.
future_dates = loaded_prophet_model.make_future_dataframe(periods=30, freq='D')

# Generate the forecast
future_forecast = loaded_prophet_model.predict(future_dates)

# Display the relevant parts of the future forecast
display(future_forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail())
joblib.dump(loaded_prophet_model, 'prophet_model.joblib')
print("Prophet model saved to prophet_model.joblib")

# Plot the forecast
fig = loaded_prophet_model.plot(future_forecast)
plt.title('Future Sales Forecast with Prophet Model')
plt.xlabel('Date')
plt.ylabel('Sales')
plt.show()

"""Summary of Feature Importances for Sales Forecasting **Models**

**Key Findings:**

Prophet stands out as the best-performing model by a significant margin, achieving the lowest RMSE and MAE. Its ability to handle seasonality, trend, and holidays makes it highly effective for this sales forecasting task.

**Feature Importance Insights:**

**Both XGBoost and Tuned Random Forest highlighted the critical importance of:**

**Recent Sales Trends** **(sales_roll3, lag1):** The most immediate past sales are highly indicative of future sales.
Day of the Week **(day_of_week_encoded):** Consistent weekly patterns significantly influence sales.
**Lag Features (lag7, lag30):** Weekly and monthly seasonality captured by these features are strong predictors.
Weather Conditions (Temperature_High (°C), **Wind_Speed (km/h)):** Certain weather variables play a notable role, though individual weather variables might not show strong linear relationships directly with sales.

**Conclusion for Stakeholders:**

Based on this comprehensive analysis, Prophet is the recommended model for sales forecasting due to its superior predictive accuracy. However, models like Random Forest and Linear Regression also provide valuable insights, particularly regarding the key factors influencing sales. Recent sales history, day of the week, and certain weather conditions are consistently identified as the most crucial drivers. Leveraging these insights can inform operational strategies, inventory management, staffing, and marketing efforts to optimize business performance.
"""

!pip install streamlit

import streamlit as st
import joblib
import pandas as pd
from prophet import Prophet

# Load trained Prophet model
model = joblib.load("prophet_model.joblib")

st.title("Restaurant Sales Forecasting with Prophet")

# Input: future date
future_date = st.date_input("Select a future date")

# Button to forecast
if st.button("Forecast Sales"):
    # Prophet expects a dataframe with 'ds' column
    future = pd.DataFrame({"ds": [pd.to_datetime(future_date)]})

    forecast = model.predict(future)
    predicted_sales = forecast["yhat"].values[0]
    lower = forecast["yhat_lower"].values[0]
    upper = forecast["yhat_upper"].values[0]

    st.subheader("Forecast Result")
    st.write(f"Predicted Sales: {predicted_sales:.2f}")
    st.write(f"Confidence Interval: {lower:.2f} – {upper:.2f}")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import joblib
# import pandas as pd
# from prophet import Prophet
# from prophet.plot import plot_plotly
# import plotly.graph_objs as go
# 
# # Load trained Prophet model
# model = joblib.load("prophet_model.joblib")
# 
# st.title("Restaurant Sales Forecasting with Prophet")
# 
# # Input: future date
# future_date = st.date_input("Select a future date")
# 
# # Button to forecast
# if st.button("Forecast Sales"):
#     # Prophet expects a dataframe with 'ds' column
#     future = pd.DataFrame({"ds": [pd.to_datetime(future_date)]})
# 
#     forecast = model.predict(future)
#     predicted_sales = forecast["yhat"].values[0]
#     lower = forecast["yhat_lower"].values[0]
#     upper = forecast["yhat_upper"].values[0]
# 
#     st.subheader("Forecast Result")
#     st.write(f"Predicted Sales: {predicted_sales:.2f}")
#     st.write(f"Confidence Interval: {lower:.2f} – {upper:.2f}")
# 
#     # Plot the forecast using plot_plotly
#     fig = plot_plotly(model, forecast)
#     st.plotly_chart(fig)
#

from prophet.plot import plot_plotly
import plotly.graph_objs as go

fig = plot_plotly(model, forecast)
st.plotly_chart(fig)